name: Build & Release

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set execute permission for build
        run: chmod +x build.sh

      - name: Read VERSION from config.sh
        id: version
        run: |
          VERSION=$(grep VERSION config.sh | cut -d'=' -f2 | tr -d '"')
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build
        run: ./build.sh

      - name: Create Git tag
        run: |
          git config user.name "xlaoyu"
          git config user.email "frank_yll@163.com"
          git tag -f $VERSION
          git push origin $VERSION --force

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ env.VERSION }}
          name: "env-init ${{ env.VERSION }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload dist files
        uses: softprops/action-gh-release@v1
        with:
          files: dist/env-init.sh,dist/env-init.sh.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
